on:
  push:
    branches: [main]

jobs:
  tests-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: corepack enable
      - run: pnpm i -D

      - name: lint
        run: biome lint .

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: pack
        run: pnpm pack

      - uses: actions/upload-artifact@v4
        with:
          name: '@benricheson101-util-pkg'
          path: ./benricheson101-util-*.tgz

  release:
    runs-on: ubuntu-latest
    needs: tests-node
    # if: github.ref_type == 'tag'

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - run: corepack enable

      - uses: actions/download-artifact@v4
        with:
          name: '@benricheson101-util-pkg'
          path: .

      - name: publish
        run: pnpm publish ./benricheson101-util-*.tgz
        env:
          NODE_AUTH_TOKEN: '${{env.NODE_AUTH_TOKEN}}'
