on:
  push:
    branches: [main]
    tags: ['*']
    paths:
      - lib
      - templates
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - tsup.config.js

  workflow_dispatch:
    # inputs:
    #   release:
    #     type: boolean
    #     description: Publish to NPM
    #     required: false
    #     default: false

jobs:
  tests-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: corepack enable
      - run: pnpm i

      - name: lint
        run: biome lint .

        # TODO: get test coverage to work with tsup builds
      - name: build
        run: pnpm tsc --noEmit false --outDir tests

      - name: test
        run: pnpm test

      - run: pnpm clean
      - run: pnpm build
      - run: pnpm pack

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: '@benricheson101-util-pkg'
          path: ./benricheson101-util-*.tgz

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: '@benricheson101-util-pkg.zip'
          subject-digest: sha256:${{steps.upload.outputs.artifact-digest}}

  release:
    runs-on: ubuntu-latest
    needs: tests-node
    if: contains(github.ref, 'refs/tags/') || inputs.release
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: corepack enable
      - run: pnpm i

      - name: build
        run: pnpm build

      - env:
          NPM_TOKEN: '${{secrets.NPM_TOKEN}}'
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

      - if: ${{inputs.release}}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: publish
        run: pnpm publish --no-git-checks --access public
        env:
          NPM_TOKEN: '${{secrets.NPM_TOKEN}}'
